export enum Tajweed {
  Wasl = "ham_wasl",
  Silent = "slnt",
  LaamShamsiyah = "laam_shamsiyah",
  MaddaNormal = "madda_normal",
  MaddaPermissible = "madda_permissible",
  MaddaNecessary = "madda_necessary",
  Qalaqah = "qalaqah",
  MaddaObligatory = "madda_obligatory",
  IkhafaShafawi = "ikhafa_shafawi",
  IdghamShafawi = "idgham_shafawi",
  Iqlab = "iqlab",
  IdghamGhunnah = "idgham_ghunnah",
  IdghamNoGhunnah = "idgham_wo_ghunnah",
  IdghamMutajanisayn = "idgham_mutajanisayn",
  IdghamMutaqaribayn = "idgham_mutaqaribayn",
  Ghunnah = "ghunnah",
  Ikhafa = "ikhafa",
}

export const TAJWEED_META = {
  [Tajweed.Wasl]: {
    id: 1,
    class: "text-tajweed-1",
    type: "hamza-wasl",
    description: "Hamzat ul Wasl",
  },
  [Tajweed.Silent]: {
    id: 2,
    class: "text-tajweed-2",
    type: "silent",
    description: "Silent",
  },
  [Tajweed.LaamShamsiyah]: {
    id: 3,
    class: "text-tajweed-3",
    type: "laam-shamsiyah",
    description: "Lam Shamsiyyah",
  },
  [Tajweed.MaddaNormal]: {
    id: 4,
    class: "text-tajweed-4",
    type: "madda-normal",
    description: "Normal Prolongation: 2 Vowels",
  },
  [Tajweed.MaddaPermissible]: {
    id: 5,
    class: "text-tajweed-5",
    type: "madda-permissible",
    description: "Permissible Prolongation: 2, 4, 6 Vowels",
  },
  [Tajweed.MaddaNecessary]: {
    id: 17,
    class: "text-tajweed-17",
    type: "madda-necesssary",
    description: "Necessary Prolongation: 6 Vowels",
  },
  [Tajweed.Qalaqah]: {
    id: 6,
    class: "text-tajweed-6",
    type: "qalaqah",
    description: "Qalaqah",
  },
  [Tajweed.MaddaObligatory]: {
    id: 7,
    class: "text-tajweed-7",
    type: "madda-obligatory",
    description: "Obligatory Prolongation: 4-5 Vowels",
  },
  [Tajweed.IkhafaShafawi]: {
    id: 8,
    class: "text-tajweed-8",
    type: "ikhafa-shafawi",
    description: "Ikhafa' Shafawi - With Meem",
  },
  [Tajweed.Ikhafa]: {
    id: 9,
    class: "text-tajweed-9",
    type: "ikhafa",
    description: "Ikhafa'",
  },
  [Tajweed.IdghamShafawi]: {
    id: 10,
    class: "text-tajweed-10",
    type: "idgham-shafawi",
    description: "Idgham Shafawi - With Meem",
  },
  [Tajweed.Iqlab]: {
    id: 11,
    class: "text-tajweed-11",
    type: "iqlab",
    description: "Iqlab",
  },
  [Tajweed.IdghamGhunnah]: {
    id: 12,
    class: "text-tajweed-12",
    type: "idgham-with-ghunnah",
    description: "Idgham - With Ghunnah",
  },
  [Tajweed.IdghamNoGhunnah]: {
    id: 13,
    class: "text-tajweed-13",
    type: "idgham-without-ghunnah",
    description: "Idgham - Without Ghunnah",
  },
  [Tajweed.IdghamMutajanisayn]: {
    id: 14,
    class: "text-tajweed-14",
    type: "idgham-mutajanisayn",
    description: "Idgham - Mutajanisayn",
  },
  [Tajweed.IdghamMutaqaribayn]: {
    id: 15,
    class: "text-tajweed-15",
    type: "idgham-mutaqaribayn",
    description: "Idgham - Mutaqaribayn",
  },
  [Tajweed.Ghunnah]: {
    id: 16,
    class: "text-tajweed-16",
    type: "ghunnah",
    description: "Ghunnah: 2 Vowels",
  },
} as const;
